version: '3.4'

services:
  mssql:
    container_name: mssql
    image: mcr.microsoft.com/mssql/server:latest
    user: root
    volumes:
      - mssql_data:/var/opt/mssql
    environment:
      SA_PASSWORD: qw12er34AA1!
      ACCEPT_EULA: Y
      TZ: UTC
      # MSSQL_PID: Express
    ports:
      - '1433:1433'
  

  artur_gde_krosi_vue.server:
    container_name: artur_gde_krosi_vue.server
    image: server:latest
    build:
      context: artur_gde_krosi_Vue.Server/
    depends_on:
      - mssql

  my-app:
    image: nginx:latest
    build: artur_gde_krosi_vue.client/
    ports:
      - "80:80"
    depends_on:
      - artur_gde_krosi_vue.server     

networks:
  app-net:

volumes:
  mssql_data: