version: '3.4'

services:
  mssql:
    container_name: mssql
    image: mssql:latest
    user: root
    build:
      context: ./mssqlDocker
      dockerfile: ./Dockerfile
    volumes:
      - mssql_data:/var/opt/mssql
    environment:
      SA_PASSWORD: qw12er34AA1!
      ACCEPT_EULA: Y
      TZ: UTC
      # MSSQL_PID: Express
    ports:
      - '1433:1433'
  

  artur_gde_krosi_vue.server:
    container_name: artur_gde_krosi_vue.server
    image: server:latest
    build:
      context: artur_gde_krosi_Vue.Server/
    depends_on:
      - mssql
    

  my-app:
    image: my-app:latest
    container_name: my-app
    build: artur_gde_krosi_vue.client/
    ports:
      - '8081:4173'


  nginx:
    image: nginx:latest
    ports:
        - "80:80"
    volumes:
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
        - ./artur_gde_krosi_vue.client/dist:/usr/share/nginx/html:ro  
    depends_on:
      - my-app
      - artur_gde_krosi_vue.server
     
    environment:
      - DB_HOST=localhost
      - DB_PORT=8081       




networks:
  app-net:

volumes:
  mssql_data: