// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using artur_gde_krosi_Vue.Server.Models.ProjecktSetings;

#nullable disable

namespace artur_gde_krosi_Vue.Server.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    partial class ApplicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("artur_gde_krosi_Vue.Server.Models.BdModel.Brend", b =>
                {
                    b.Property<string>("BrendId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BrendId");

                    b.ToTable("Brends");
                });

            modelBuilder.Entity("artur_gde_krosi_Vue.Server.Models.BdModel.Image", b =>
                {
                    b.Property<string>("ImageId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ImageSrc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Index")
                        .HasColumnType("int");

                    b.Property<string>("ProductId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ImageId");

                    b.HasIndex("ProductId");

                    b.ToTable("Images");
                });

            modelBuilder.Entity("artur_gde_krosi_Vue.Server.Models.BdModel.ImageVariant", b =>
                {
                    b.Property<string>("ImageVariantId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<byte[]>("ImageData")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("VariantId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ImageVariantId");

                    b.HasIndex("VariantId");

                    b.ToTable("ImageVariants");
                });

            modelBuilder.Entity("artur_gde_krosi_Vue.Server.Models.BdModel.ModelKrosovock", b =>
                {
                    b.Property<string>("ModelKrosovockId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("BrendID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ModelKrosovockId");

                    b.HasIndex("BrendID");

                    b.ToTable("ModelKrosovocks");
                });

            modelBuilder.Entity("artur_gde_krosi_Vue.Server.Models.BdModel.Product", b =>
                {
                    b.Property<string>("ProductId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ModelKrosovockId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("prise")
                        .HasColumnType("float");

                    b.HasKey("ProductId");

                    b.HasIndex("ModelKrosovockId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("artur_gde_krosi_Vue.Server.Models.BdModel.Variant", b =>
                {
                    b.Property<string>("VariantId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProductId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("externalCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("prise")
                        .HasColumnType("float");

                    b.Property<int>("quantityInStock")
                        .HasColumnType("int");

                    b.Property<double>("shoeSize")
                        .HasColumnType("float");

                    b.HasKey("VariantId");

                    b.HasIndex("ProductId");

                    b.ToTable("Variants");
                });

            modelBuilder.Entity("artur_gde_krosi_Vue.Server.Models.BdModel.Image", b =>
                {
                    b.HasOne("artur_gde_krosi_Vue.Server.Models.BdModel.Product", "Product")
                        .WithMany("Images")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("artur_gde_krosi_Vue.Server.Models.BdModel.ImageVariant", b =>
                {
                    b.HasOne("artur_gde_krosi_Vue.Server.Models.BdModel.Variant", "Variant")
                        .WithMany("ImageVariant")
                        .HasForeignKey("VariantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Variant");
                });

            modelBuilder.Entity("artur_gde_krosi_Vue.Server.Models.BdModel.ModelKrosovock", b =>
                {
                    b.HasOne("artur_gde_krosi_Vue.Server.Models.BdModel.Brend", "Brend")
                        .WithMany("ModelKrosovocks")
                        .HasForeignKey("BrendID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Brend");
                });

            modelBuilder.Entity("artur_gde_krosi_Vue.Server.Models.BdModel.Product", b =>
                {
                    b.HasOne("artur_gde_krosi_Vue.Server.Models.BdModel.ModelKrosovock", "ModelKrosovock")
                        .WithMany("Products")
                        .HasForeignKey("ModelKrosovockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ModelKrosovock");
                });

            modelBuilder.Entity("artur_gde_krosi_Vue.Server.Models.BdModel.Variant", b =>
                {
                    b.HasOne("artur_gde_krosi_Vue.Server.Models.BdModel.Product", "Product")
                        .WithMany("Variants")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("artur_gde_krosi_Vue.Server.Models.BdModel.Brend", b =>
                {
                    b.Navigation("ModelKrosovocks");
                });

            modelBuilder.Entity("artur_gde_krosi_Vue.Server.Models.BdModel.ModelKrosovock", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("artur_gde_krosi_Vue.Server.Models.BdModel.Product", b =>
                {
                    b.Navigation("Images");

                    b.Navigation("Variants");
                });

            modelBuilder.Entity("artur_gde_krosi_Vue.Server.Models.BdModel.Variant", b =>
                {
                    b.Navigation("ImageVariant");
                });
#pragma warning restore 612, 618
        }
    }
}
